/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';

// Create Virtual Routes

const RoomsLazyImport = createFileRoute('/rooms')();

// Create/Update Routes

const RoomsLazyRoute = RoomsLazyImport.update({
  path: '/rooms',
  getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/rooms.lazy').then(d => d.Route));

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/rooms': {
      preLoaderRoute: typeof RoomsLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexRoute, RoomsLazyRoute]);

/* prettier-ignore-end */
